### PR TITLE
Yuliia.m tc111 done with test case

### PR DESCRIPTION
**Pull request by YuliiaMashkina**
added some awesome codes

### CODE REVIEW

**Review by SF001User — COMMENTED** [review]
cool code , was it the thing we talked about on login functionality ?

**Review by MohamedBoghdadi — COMMENTED** [review]
Good Job

**Review by atila-a — COMMENTED** [review]
reviewed, 1,2,3,4,5

**Review by mousa-adolai — COMMENTED** [review]
Awesome code. We did the thing!

**Review by inesa7 — COMMENTED** [review]
great job

**Comment by tamtaoda** [comment]
great job!!!

**Review by SF001User — APPROVED** [review]
let's merge it, approved!

**Review by mousa-adolai — APPROVED** [review]
Approved for merge.

**Review by atila-a — APPROVED** [review]
Merge it and approved

**Review by MohamedBoghdadi — APPROVED** [review]
everything looks good, Approved

**Comment by SBNPTV** [comment]
nice, ready to merge

**Review by inesa7 — COMMENTED** [review]
approved

**Pull request merged**
