### PR TITLE
B23user completed TC121

### PR DESCRIPTION
**Pull request by SF001User**
MADE A booboo to start with but fixed it by rolling back the staged changes and opening a branch and continuing with GitHub flow

### CODE REVIEW

**Review by inesa7 — COMMENTED** [review]
awesome code

**Review by YuliiaMashkina — COMMENTED** [review]
Lets learn about more blocks

**Review by atila-a — CHANGES_REQUESTED** [review]
awesome car class
can you add constructor here please

**Review by inesa7 — CHANGES_REQUESTED** [review]
can you add more code please

**Review by atila-a — APPROVED** [review]
great job, thanks for changes

**Pull request merged**
