### PR TITLE
Mohamed3 login functionality

### PR DESCRIPTION
**Pull request by MohamedBoghdadi**
done

### CODE REVIEW

**Review by MohamedBoghdadi — COMMENTED** [review]
reviewed

**Review by YuliiaMashkina — COMMENTED** [review]
Lets add more lines

**Review by inesa7 — APPROVED** [review]
great job

**Review by YuliiaMashkina — APPROVED** [review]
Good code, approving everything

**Review by inesa7 — COMMENTED** [review]
new line looks good

**Review by YuliiaMashkina — COMMENTED** [review]
Awesome code

**Pull request merged**
